-- ByteLearn lesson seed
-- Run supabase.sql first, then run this file in Supabase SQL Editor.

insert into public.lessons
(id, category, title, subtitle, tag, difficulty, scenes, tags, published)
values
('llm','AI','What is an LLM?','The engine behind modern AI','AI BASICS','Beginner','[{"kind":"title","title":"WHAT IS AN LLM?","body":"A machine that learns patterns in language."},{"kind":"flow","title":"Think of it like this","items":["Lots of text","↓","Patterns","↓","Predictions","↓","Useful answers"]},{"kind":"text","title":"Large Language Model","body":"During training, an LLM learns statistical patterns in huge amounts of text. It generates responses by predicting tokens repeatedly."},{"kind":"summary","title":"TL;DR","body":"An LLM is a pattern-learning system that generates language one token at a time."},{"kind":"quiz","question":"What does an LLM primarily learn?","options":["How to store files","Patterns in language","How to build phones"],"answer":1}]'::jsonb,ARRAY[]::text[],true),
('rag','AI','What is RAG?','Give an AI system useful external context','AI','Beginner','[{"kind":"title","title":"RAG","body":"Retrieval-Augmented Generation"},{"kind":"flow","title":"Without RAG","items":["Question","↓","Model knowledge","↓","Answer"]},{"kind":"flow","title":"With RAG","items":["Question","↓","Search documents","↓","Relevant context","↓","AI answer"]},{"kind":"text","title":"Why it matters","body":"RAG lets an AI system retrieve current or private information before generating an answer."},{"kind":"quiz","question":"What does the R in RAG stand for?","options":["Reasoning","Retrieval","Rendering"],"answer":1}]'::jsonb,ARRAY[]::text[],true),
('agent','AI','What is an AI Agent?','A chatbot talks. An agent can take action.','AI AGENTS','Beginner','[{"kind":"title","title":"AI AGENTS","body":"AI that can reason, use tools and act."},{"kind":"flow","title":"The loop","items":["Goal","↓","Plan","↓","Use a tool","↓","Observe","↓","Act"]},{"kind":"text","title":"Example","body":"“Find the cheapest flight.” An agent could search flights, compare options and return the best match."},{"kind":"summary","title":"TL;DR","body":"An AI agent combines a model with tools and an action loop."},{"kind":"quiz","question":"Which is closest to an AI agent?","options":["A static FAQ","An AI system that can use tools","A database"],"answer":1}]'::jsonb,ARRAY[]::text[],true),
('tokens','AI','What are AI Tokens?','The units an LLM processes','AI BASICS','Beginner','[{"kind":"title","title":"TOKENS","body":"AI models usually process text as tokens, not whole sentences."},{"kind":"flow","title":"Text becomes pieces","items":["“Hello world!”","↓","“Hello” + “ world” + “!”","↓","Token IDs"]},{"kind":"code","title":"Conceptually","code":"Text → tokenizer → token IDs\n\n[15496, 995, 0]"},{"kind":"text","title":"Why care?","body":"Token counts affect context limits, latency and the cost of many AI APIs."},{"kind":"quiz","question":"Why do token counts matter?","options":["They affect AI context and cost","They change your screen size","They are passwords"],"answer":0}]'::jsonb,ARRAY[]::text[],true),
('api','Programming','What is an API?','How software talks to other software','PROGRAMMING','Beginner','[{"kind":"title","title":"WHAT IS AN API?","body":"A defined way for software to request something from another system."},{"kind":"flow","title":"Restaurant analogy","items":["You → Waiter → Kitchen","Request → API → Service","Result ← API ← Service"]},{"kind":"code","title":"A simple request","code":"GET /users/42\n\n→ 200 OK\n{ \"name\": \"Maya\" }"},{"kind":"text","title":"Why APIs matter","body":"Teams can build systems independently while agreeing on request and response formats."},{"kind":"quiz","question":"What does an API primarily provide?","options":["A UI design","A communication contract","A hard drive"],"answer":1}]'::jsonb,ARRAY[]::text[],true),
('docker','Cloud','What is Docker?','Package an app with what it needs to run','CLOUD','Beginner','[{"kind":"title","title":"DOCKER","body":"“It works on my machine” — solved."},{"kind":"flow","title":"The idea","items":["App + dependencies","↓","Container","↓","Run consistently"]},{"kind":"text","title":"The payoff","body":"A container packages an application and its dependencies into a portable unit."},{"kind":"summary","title":"TL;DR","body":"Docker makes software environments more reproducible and portable."},{"kind":"quiz","question":"What does a container package?","options":["Only the UI","An app and its dependencies","Only a database"],"answer":1}]'::jsonb,ARRAY[]::text[],true),
('cache','System Design','What is Caching?','How apps become much faster','SYSTEM DESIGN','Beginner','[{"kind":"title","title":"CACHING","body":"Don’t repeatedly fetch what you already know."},{"kind":"flow","title":"No cache","items":["User","↓","Server","↓","Database","↓","Response"]},{"kind":"flow","title":"With cache","items":["User","↓","Cache","⚡","Response","↓","DB when needed"]},{"kind":"text","title":"The trade-off","body":"Caches improve speed and reduce database load, but cached data can become stale."},{"kind":"quiz","question":"What is a common benefit of caching?","options":["More database work","Lower latency","More network hops"],"answer":1}]'::jsonb,ARRAY[]::text[],true),
('sql','Programming','SQL vs NoSQL','Different ways to model data','DATA','Beginner','[{"kind":"title","title":"SQL vs NoSQL","body":"Structured tables vs more flexible data models."},{"kind":"flow","title":"SQL","items":["Tables","↓","Rows + columns","↓","Relationships"]},{"kind":"flow","title":"NoSQL","items":["Documents / key-value","↓","Flexible structure","↓","Scale patterns"]},{"kind":"text","title":"Neither is better","body":"The right choice depends on access patterns, consistency needs and scale."},{"kind":"quiz","question":"Which is a relational database language?","options":["SQL","HTML","CSS"],"answer":0}]'::jsonb,ARRAY[]::text[],true),
('queue','System Design','What is a Message Queue?','Handle work asynchronously','SYSTEM DESIGN','Beginner','[{"kind":"title","title":"MESSAGE QUEUES","body":"Let one system hand work to another without waiting."},{"kind":"flow","title":"The idea","items":["Producer","↓","Queue","↓","Consumer"]},{"kind":"text","title":"Why use one?","body":"Queues absorb traffic spikes and let consumers process work independently."},{"kind":"summary","title":"TL;DR","body":"A queue decouples producers from consumers and smooths bursts of work."},{"kind":"quiz","question":"What is a queue useful for?","options":["Buffering work","Rendering CSS","Replacing every database"],"answer":0}]'::jsonb,ARRAY[]::text[],true),
('cdn','Cloud','What is a CDN?','Move content closer to your users','CLOUD','Beginner','[{"kind":"title","title":"CDN","body":"Content Delivery Network"},{"kind":"flow","title":"Without a CDN","items":["User in India","↓","Origin in US","↓","Longer trip"]},{"kind":"flow","title":"With a CDN","items":["User","↓","Nearby edge","⚡","Cached content"]},{"kind":"text","title":"The payoff","body":"A CDN can reduce latency by serving static content from locations closer to users."},{"kind":"quiz","question":"What is a CDN mainly trying to reduce?","options":["Latency","Screen brightness","Code indentation"],"answer":0}]'::jsonb,ARRAY[]::text[],true),
('ai-credits-vs-tokens','AI','AI Credits vs Tokens','Understand the difference between what AI models process and what AI services charge for','AI BASICS','Beginner','[{"kind":"title","title":"AI CREDITS VS TOKENS","body":"Tokens are pieces of text an AI model processes. AI credits are a usage unit that a product or platform may use to measure or price AI features."},{"kind":"flow","title":"Tokens","items":["Your prompt","↓","Tokenizer","↓","Token IDs","↓","Model processes them"]},{"kind":"flow","title":"AI credits","items":["AI feature","↓","Usage measured","↓","Credits consumed","↓","Remaining balance"]},{"kind":"text","title":"The key difference","body":"Tokens describe model input and output. Credits are a product-level accounting unit. One credit does not universally equal a fixed number of tokens; the conversion depends on the service."},{"kind":"callout","title":"WHY IT MATTERS","body":"Knowing the difference helps you understand AI API pricing, usage limits and why two products can charge differently for similar AI tasks."},{"kind":"text","title":"Example","body":"An AI app might charge credits for generating an image, while an LLM API might bill directly for input and output tokens. Credits can bundle or abstract away several underlying costs."},{"kind":"quiz","question":"Which statement is correct?","options":["Tokens are pieces of text processed by models; credits are a service-level usage unit","One AI credit always equals exactly 1,000 tokens everywhere","Tokens and credits are always the same thing"],"answer":0}]'::jsonb,ARRAY['AI','tokens','credits','pricing']::text[],true),
on conflict (id) do update set
  category=excluded.category,
  title=excluded.title,
  subtitle=excluded.subtitle,
  tag=excluded.tag,
  difficulty=excluded.difficulty,
  scenes=excluded.scenes,
  tags=excluded.tags,
  published=excluded.published;
